Repository andreaswachs/BDSA2021-FinalProject, pull requests merged in 2021-11, with the labels that each got.

#1 Add templates for issues and PRs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/other_issues.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#2 Feature/code skeleton
  .github/workflows/unit_tests_on_push.yml
  BDSA2021-FinalProject.sln
  Makefile
  WebService.Core.Tests/UnitTest1.cs
  WebService.Core.Tests/WebService.Core.Tests.csproj
  WebService.Core/App.razor
  WebService.Core/Data/WeatherForecast.cs
  WebService.Core/Data/WeatherForecastService.cs
  WebService.Core/Pages/Counter.razor
  WebService.Core/Pages/Error.cshtml
  WebService.Core/Pages/Error.cshtml.cs
  WebService.Core/Pages/FetchData.razor
  WebService.Core/Pages/Index.razor
  WebService.Core/Pages/_Host.cshtml
  WebService.Core/Pages/_Layout.cshtml
  WebService.Core/Program.cs
  WebService.Core/Properties/launchSettings.json
  WebService.Core/Shared/MainLayout.razor
  WebService.Core/Shared/MainLayout.razor.css
  WebService.Core/Shared/NavMenu.razor
  WebService.Core/Shared/NavMenu.razor.css
  WebService.Core/Shared/SurveyPrompt.razor
  WebService.Core/WebService.Core.csproj
  WebService.Core/_Imports.razor
  WebService.Core/appsettings.Development.json
  WebService.Core/appsettings.json
  WebService.Core/wwwroot/css/bootstrap/bootstrap.min.css
  WebService.Core/wwwroot/css/bootstrap/bootstrap.min.css.map
  WebService.Core/wwwroot/css/open-iconic/FONT-LICENSE
  WebService.Core/wwwroot/css/open-iconic/ICON-LICENSE
  WebService.Core/wwwroot/css/open-iconic/README.md
  WebService.Core/wwwroot/css/open-iconic/font/css/open-iconic-bootstrap.min.css
  WebService.Core/wwwroot/css/open-iconic/font/fonts/open-iconic.eot
  WebService.Core/wwwroot/css/open-iconic/font/fonts/open-iconic.otf
  WebService.Core/wwwroot/css/open-iconic/font/fonts/open-iconic.svg
  WebService.Core/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf
  WebService.Core/wwwroot/css/open-iconic/font/fonts/open-iconic.woff
  WebService.Core/wwwroot/css/site.css
  WebService.Core/wwwroot/favicon.ico
  WebService.Entities/Class1.cs
  WebService.Entities/WebService.Entities.csproj
  WebService.Infrastructure.Tests/UnitTest1.cs
  WebService.Infrastructure.Tests/WebService.Infrastructure.Tests.csproj
  WebService.Infrastructure/Class1.cs
  WebService.Infrastructure/WebService.Infrastructure.csproj
Labels: enhancement

#35 Repository
  WebService.Core/Shared/AuthorDTO.cs
  WebService.Core/Shared/ILanguageRepository.cs
  WebService.Core/Shared/ILevelRespository.cs
  WebService.Core/Shared/IMaterialRepository.cs
  WebService.Core/Shared/IMediaRepository.cs
  WebService.Core/Shared/IProgrammingLanguageRespository.cs
  WebService.Core/Shared/IRatingRepository.cs
  WebService.Core/Shared/ITagRepository.cs
  WebService.Core/Shared/MaterialDTO.cs
  WebService.Core/Shared/SearchInput.cs
  WebService.Core/Shared/Status.cs
  WebService.Core/Shared/TagDTO.cs
  WebService.Entities/Author.cs
  WebService.Entities/GlobalUsings.cs
  WebService.Entities/Language.cs
  WebService.Entities/Level.cs
  WebService.Entities/Material.cs
  WebService.Entities/Media.cs
  WebService.Entities/ProgrammingLanguage.cs
  WebService.Entities/Rating.cs
  WebService.Entities/Tag.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/TestVariables.cs
  WebService.Infrastructure.Tests/GlobalUsings.cs
  WebService.Infrastructure.Tests/WebService.Infrastructure.Tests.csproj
  WebService.Infrastructure/Class1.cs
  WebService.Infrastructure/Context.cs
  WebService.Infrastructure/IContext.cs
  WebService.Infrastructure/LanguageRepository.cs
  WebService.Infrastructure/LevelRepository.cs
  WebService.Infrastructure/MaterialRepository.cs
  WebService.Infrastructure/MediaRepository.cs
  WebService.Infrastructure/ProgrammingLanguageRepository.cs
  WebService.Infrastructure/RatingRepository.cs
  WebService.Infrastructure/TagRepository.cs
Labels: enhancement

#37 Search
  WebService.Core/Server/Pages/Error.cshtml.cs
  WebService.Core/Shared/ILanguageRepository.cs
  WebService.Core/Shared/ILevelRespository.cs
  WebService.Core/Shared/IMaterialRepository.cs
  WebService.Core/Shared/IMediaRepository.cs
  WebService.Core/Shared/IProgrammingLanguageRespository.cs
  WebService.Core/Shared/IRatingRepository.cs
  WebService.Core/Shared/ITagRepository.cs
  WebService.Core/Shared/MaterialDTO.cs
  WebService.Core/Shared/RatingDTO.cs
  WebService.Core/Shared/SearchForm.cs
  WebService.Core/Shared/TagDTO.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/TestVariables.cs
  WebService.Infrastructure.Tests/GlobalUsings.cs
  WebService.Infrastructure.Tests/SearchAlgorithmTests/SearchAlgorithmTests.cs
  WebService.Infrastructure.Tests/UnitTest1.cs
  WebService.Infrastructure/Context.cs
  WebService.Infrastructure/GlobalUsings.cs
  WebService.Infrastructure/LanguageRepository.cs
  WebService.Infrastructure/LevelRepository.cs
  WebService.Infrastructure/MaterialRepository.cs
  WebService.Infrastructure/MediaRepository.cs
  WebService.Infrastructure/ProgrammingLanguageRepository.cs
  WebService.Infrastructure/RatingRepository.cs
  WebService.Infrastructure/SearchAlgorithm.cs
  WebService.Infrastructure/TagRepository.cs
Labels: feature

#38 Repository
  WebService.Core/Shared/CategoryDTO.cs
  WebService.Core/Shared/IAuthorRepository.cs
  WebService.Core/Shared/ICategoryRepository.cs
  WebService.Core/Shared/ILanguageRepository.cs
  WebService.Core/Shared/ILevelRespository.cs
  WebService.Core/Shared/IMaterialRepository.cs
  WebService.Core/Shared/IMediaRepository.cs
  WebService.Core/Shared/IProgrammingLanguageRespository.cs
  WebService.Core/Shared/IRatingRepository.cs
  WebService.Core/Shared/ITagRepository.cs
  WebService.Core/Shared/LevelDTO.cs
  WebService.Entities/Author.cs
  WebService.Entities/Category.cs
  WebService.Entities/Language.cs
  WebService.Entities/Level.cs
  WebService.Entities/Media.cs
  WebService.Entities/ProgrammingLanguage.cs
  WebService.Entities/Rating.cs
  WebService.Entities/Tag.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/AuthorRepositoryTest.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/LanguageRepositoryTests.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/LevelRepositoryTests.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/MediaRepositoryTests.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/ProgrammingLanguageRepositoryTests.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/RatingRepositoryTests.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/TagRepositoryTests.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/TestVariables.cs
  WebService.Infrastructure.Tests/GlobalUsings.cs
  WebService.Infrastructure.Tests/WebService.Infrastructure.Tests.csproj
  WebService.Infrastructure/AuthorRepository.cs
  WebService.Infrastructure/CategoryRepository.cs
  WebService.Infrastructure/Context.cs
  WebService.Infrastructure/IContext.cs
  WebService.Infrastructure/LanguageRepository.cs
  WebService.Infrastructure/LevelRepository.cs
  WebService.Infrastructure/MaterialRepository.cs
  WebService.Infrastructure/MediaRepository.cs
  WebService.Infrastructure/ProgrammingLanguageRepository.cs
  WebService.Infrastructure/RatingRepository.cs
  WebService.Infrastructure/TagRepository.cs
Labels: enhancement

#40 Feature/dbaccess
  README.md
  WebService.Core/Server/ContextFactory.cs
  WebService.Core/Server/WebService.Core.Server.csproj
  WebService.Entities/Context.cs
  WebService.Entities/IContext.cs
  WebService.Entities/Migrations/ContextModelSnapshot.cs
  WebService.Entities/WebService.Entities.csproj
  WebService.Infrastructure/Context.cs
  WebService.Infrastructure/WebService.Infrastructure.csproj
  migrate.ps1
  start_db.ps1
  update_db.ps1
Labels: enhancement, Back end

#47 Filter search
  WebService.Core.Client.Tests/IndexTest.cs
  WebService.Core.Client.Tests/UnitTest1.cs
  WebService.Core.Client.Tests/WebService.Core.Client.Tests.csproj
  WebService.Core/Client/Pages/Index.razor
Labels: enhancement, Front end
