Repository andreaswachs/BDSA2021-FinalProject, pull requests merged in 2021-12, with the labels that each got.

#52 Removed old migrations and added the new one, server looks good only …
  WebService.Entities/Context.cs
  WebService.Entities/Migrations/20211201125745_init.cs
  WebService.Entities/Migrations/20211201140215_UpdatedEntities.Designer.cs
  WebService.Entities/Migrations/20211201140215_UpdatedEntities.cs
  WebService.Entities/Migrations/20211201140523_NAME.Designer.cs
  WebService.Entities/Migrations/20211201140523_NAME.cs
  WebService.Entities/Migrations/20211201141114_EfUpdate.Designer.cs
  WebService.Entities/Migrations/20211201141114_EfUpdate.cs
  WebService.Entities/Migrations/20211201141337_SomeNewMigration.Designer.cs
  WebService.Entities/Migrations/20211201141337_SomeNewMigration.cs
  WebService.Entities/Migrations/20211201142046_EfUpdateNew.Designer.cs
  WebService.Entities/Migrations/20211201142046_EfUpdateNew.cs
  WebService.Entities/Migrations/20211201143240_EfUpdateNew1.Designer.cs
  WebService.Entities/Migrations/20211201143240_EfUpdateNew1.cs
  WebService.Entities/Migrations/20211203133620_mig.Designer.cs
  WebService.Entities/Migrations/20211203133620_mig.cs
  WebService.Entities/Migrations/ContextModelSnapshot.cs
  WebService.Entities/WebService.Entities.csproj
Labels: enhancement, Back end

#56 Show material
  WebService.Core/Client/Pages/Index.razor
  WebService.Core/Client/Shared/MainLayout.razor
  WebService.Core/Client/wwwroot/css/app.css
  WebService.Core/Shared/MaterialDTO.cs
  WebService.Entities/Migrations/20211203133620_mig.cs
  WebService.Entities/Migrations/20211203154952_BDSABTGMigrations.Designer.cs
  WebService.Entities/Migrations/20211203154952_BDSABTGMigrations.cs
Labels: enhancement, Front end

#58 fixed migrations (again)
  WebService.Entities/Migrations/20211203122315_Migration03122021.cs
  WebService.Entities/Migrations/20211203154952_BDSABTGMigrations.Designer.cs
  WebService.Entities/Migrations/20211203154952_BDSABTGMigrations.cs
  WebService.Entities/Migrations/20211203171840_BDSA.Designer.cs
  WebService.Entities/Migrations/20211203171840_BDSA.cs
  WebService.Entities/WebService.Entities.csproj
Labels: enhancement, Back end

#61 Deleted WevService.Core.sln
  WebService.Core/Server/Program.cs
  WebService.Core/WebService.Core.sln
  WebService.Infrastructure/ISearch.cs
  WebService.Infrastructure/SearchAlgorithm.cs
Labels: enhancement

#62 GUI is fully implemented
  WebService.Core/Client/Pages/Index.razor
  WebService.Core/Client/Shared/MainLayout.razor
  WebService.Core/Server/Controllers/SearchController.cs
Labels: Front end

#63 Feature/materialrepo read searchform
  WebService.Entities/Material.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/MaterialRepositoryTests.cs
  WebService.Infrastructure.Tests/ContextRepositoryTests/TestVariables.cs
  WebService.Infrastructure.Tests/WebService.Infrastructure.Tests.csproj
  WebService.Infrastructure/MaterialRepository.cs
Labels: enhancement, Back end

#65 Added extension Methods:
  WebService.Core/Client/Pages/Index.razor
  WebService.Core/Shared/MaterialDTO.cs
Labels: enhancement

#66 Make ReadAsync async
  WebService.Entities/Material.cs
  WebService.Infrastructure/MaterialRepository.cs
Labels: bug, Back end

#68 Added Tests for material's extension methods
  WebService.Core.Shared.Tests/MaterialDTOTests.cs
  WebService.Core.Shared.Tests/UnitTest1.cs
  WebService.Core/Shared/MaterialDTO.cs
Labels: Test

#73 test of mock http client
  WebService.Core.Client.Tests/IndexTest.cs
  WebService.Core.Client.Tests/WebService.Core.Client.Tests.csproj
Labels: Front end, Test

#76 GUi responses to error 404 when searching
  WebService.Core/Client/Pages/Index.razor
Labels: Front end

#74 fixed migrations part 100
  WebService.Entities/Migrations/20211208152937_BTG.Designer.cs
  WebService.Entities/Migrations/20211208152937_BTG.cs
  WebService.Entities/Migrations/ContextModelSnapshot.cs
Labels: Back end

#78 Enable concurrent workflows on a per branch basis
  .github/workflows/unit_tests_on_push.yml
Labels: enhancement, DevOps

#80 Fixed Front end issues.
  WebService.Core.Client.Tests/IndexTest.cs
  WebService.Core/Client/Pages/Index.razor
  WebService.Core/Client/wwwroot/index.html
Labels: enhancement, Front end, feature

#82 Fixed all controllers with returning correct item
  WebService.Core/Server/Controllers/LanguageController.cs
  WebService.Core/Server/Controllers/LevelController.cs
  WebService.Core/Server/Controllers/MaterialController.cs
  WebService.Core/Server/Controllers/MediaController.cs
  WebService.Core/Server/Controllers/ProgrammingLanguageController.cs
  WebService.Core/Server/Controllers/SearchController.cs
  WebService.Core/Server/Controllers/TagController.cs
Labels: bug

#83 fixed alignment of items on gui
  WebService.Core/Client/Pages/Index.razor
  WebService.Core/Client/wwwroot/index.html
  WebService.Core/Shared/MaterialDTO.cs
Labels: Front end

#88 Fixes
  .vscode/settings.json
  WebService.Infrastructure/SearchAlgorithm.cs
Labels: enhancement

#89 clears search results after each search
  WebService.Core/Client/Pages/Index.razor
  WebService.Core/Server/ContextFactory.cs
  WebService.Core/Shared/MaterialDTO.cs
Labels: bug, Front end

#90 Feature/more faithful materials
  WebService.Core.Server.Tests/ModelTests/ContentGeneratorTests.cs
  WebService.Core/Server/Model/ContentGenerator.cs
  WebService.Core/Server/Model/SeedExtensions.cs
  WebService.Core/Server/Program.cs
  WebService.Core/Server/WebService.Core.Server.csproj
  data/authors.csv
  data/danish.corpus.txt
  data/english.corpus.txt
  data/italian.corpus.txt
  data/languages.csv
  data/russian.corpus.txt
Labels: enhancement, Back end

#97 Add start script and change README
  README.md
  WebService.Core/Server/Model/ContentGenerator.cs
  WebService.Core/Server/Model/SeedExtensions.cs
  start.ps1
Labels: documentation, enhancement, Back end

#104 Feature/imporved startup script
  README.md
  open_delayed_browser.ps1
  start.ps1
Labels: feature

#106 Mention swagger in README
  README.md
Labels: documentation

#107 Update README
  README.md
Labels: documentation
